vim.keymap.set("n", "<leader>pv", "<cmd>lua MiniFiles.open()<CR>")

vim.keymap.set("n", "<Esc>", "<cmd>nohlsearch<CR>")
vim.keymap.set("n", "<leader>glmr", "<cmd>!glab mr create --web --no-editor --fill<CR>")
vim.keymap.set("n", "<leader>fr", [[:%s/\<<C-r><C-w>\>/<C-r><C-w>/gI<Left><Left><Left>]])

-- local builtin = require('telescope.builtin')
-- vim.keymap.set('n', '<leader>pf', builtin.find_files, {})
-- vim.keymap.set('n', '<leader>lg', builtin.live_grep, {})
-- vim.keymap.set('n', '<C-p>', builtin.git_files, {})
-- vim.keymap.set('n', '<leader>pws', function()
--   local word = vim.fn.expand("<cword>")
--   builtin.grep_string({ search = word })
-- end)
-- vim.keymap.set('n', '<leader>pWs', function()
--   local word = vim.fn.expand("<cWORD>")
--   builtin.grep_string({ search = word })
-- end)
-- vim.keymap.set('n', '<leader>ps', function()
--   builtin.grep_string({ search = vim.fn.input("Grep > ") })
-- end)
-- vim.keymap.set('n', '<leader>fg', builtin.live_grep, {})
-- vim.keymap.set('n', '<leader>vh', builtin.help_tags, {})
-- vim.keymap.set('n', '<leader>pp', builtin.pickers, {})
