vim.keymap.set("n", "<leader>pv", "<cmd>lua MiniFiles.open()<CR>")

vim.keymap.set("n", "<Esc>", "<cmd>nohlsearch<CR>")
vim.keymap.set("n", "<leader>glmr", "<cmd>!glab mr create --web --no-editor --fill<CR>")
vim.keymap.set("n", "<leader>fr", [[:%s/\<<C-r><C-w>\>/<C-r><C-w>/gI<Left><Left><Left>]])

local fzf = require("fzf-lua")
vim.keymap.set("n", "<leader>pf", fzf.files, {})
vim.keymap.set("n", "<leader>lg", fzf.live_grep, {})
vim.keymap.set('n', '<C-p>', "<cmd>FzfLua git_files<CR>", {})
vim.keymap.set("n", "<leader>pws", fzf.grep_cword, {})
vim.keymap.set("n", "<leader>pWs", fzf.grep_cWORD, {})
vim.keymap.set("n", "<leader>fg", fzf.live_grep, {})
vim.keymap.set("n", "<leader>vh", fzf.helptags, {})
vim.keymap.set("n", "<leader>pp", fzf.builtin, {})
vim.keymap.set("n", "<leader>gr", fzf.lsp_references, {})
